DEEPSORT:
  REID_CKPT: "deep_sort_pytorch/deep_sort/deep/checkpoint/ckpt.t7"
  MAX_DIST: 0.2
  MIN_CONFIDENCE: 0.001
  NMS_MAX_OVERLAP: 0.5
  MAX_IOU_DISTANCE: 0.3
  MAX_AGE: 20
  N_INIT: 1
  NN_BUDGET: 100
  

# tracker.py
#metric : nn_matching.NearestNeighborDistanceMetric
#        A distance metric for measurement-to-track association.
#max_age : int
#        Maximum number of missed misses before a track is deleted.
#n_init : int
#        Number of consecutive detections before the track is confirmed. The
#        track state is set to `Deleted` if a miss occurs within the first
#        `n_init` frames.
# nn_matching.py
#    matching_threshold: float
#        The matching threshold. Samples with larger distance are considered an
#        invalid match.
#    budget : Optional[int]
#        If not None, fix samples per class to at most this number. Removes
#        the oldest samples when the budget is reached.